# ansible 2.4
---
  - name: Setup SapMachine Master server
    hosts: SapMachineMaster
    gather_facts: False
    pre_tasks:
      - name: 'install python2'
        raw: sudo apt-get -qq -y --no-install-recommends install python
    vars:
      ansible_user: ubuntu
      ansible_ssh_private_key_file: SapMachine.pem
      slave_jar_version: 3.16
      jenkins_master_url: https://ci.sapmachine.net/computer/agent-linux-x86_64-1/slave-agent.jnlp
      jenkins_slave_name: agent-linux-x86_64-1

    tasks:

      - name: install docker
        apt:
          name: docker.io
          state: latest
          update_cache: yes
          install_recommends: no
        become: yes

      - name: install docker-compose
        apt:
          name: docker-compose
          state: latest
          install_recommends: no
        become: yes

      - name: install OpenJDK 8 JRE
        apt:
         name: openjdk-8-jre
         state: latest
         install_recommends: no
        become: yes

      - name: create sapmachine group
        group:
          name: sapmachine
          state: present
        become: yes

      - name: create sapmachine user
        user:
          name: sapmachine
          comment: "SapMachine user"
          group: sapmachine
          groups: sapmachine, docker
        become: yes

      - name: create jenkins group
        group:
          name: jenkins
          state: present
        become: yes

      - name: create jenkins user
        user:
          name: jenkins
          comment: "Jenkins user"
          groups: jenkins, docker
        become: yes

      - name: copy sapmachine_master files
        synchronize:
          src: ../../
          dest: /home/sapmachine/sapmachine_master
          recursive: yes
          rsync_opts:
            - "--exclude=.git*"
            - "--exclude=ansible"
        become: yes

      - name: set ownership of sapmachine_master
        file:
          path: /home/sapmachine/sapmachine_master
          owner: sapmachine
          group: sapmachine
          recurse: yes
        become: yes

      - name: create Jenkins Slave home directory
        file:
          path: /home/jenkins/slave-home
          state: directory
        become: yes
        become_user: jenkins

      - name: download Jenkins Slave jar
        get_url:
          url: "https://repo.jenkins-ci.org/public/org/jenkins-ci/main/remoting/{{ slave_jar_version }}/remoting-{{ slave_jar_version }}.jar"
          dest: /home/jenkins/slave.jar
        become: yes
        become_user: jenkins

      - name: copy Jenkins Slave files
        synchronize:
          src: ../ci-slave-local/start-slave.sh
          dest: /home/jenkins/start-slave.sh
        become: yes
        become_user: jenkins

      - name: stop all running docker container
        shell: docker stop $(docker ps -a -q)
        become: yes
        become_user: sapmachine
        ignore_errors: yes

      - name: stop all Java processes
        command: killall -9 java
        become: yes
        ignore_errors: yes

      - name: start the docker container
        command: docker-compose -f ./compose.yml up -d --build
        args:
          chdir: /home/sapmachine/sapmachine_master
        become: yes
        become_user: sapmachine
        environment:

      - name: wait for Jenkins Master to come up
        command: docker exec ci bash /usr/share/jenkins/read-sapmachine-pw.sh
        become: yes
        become_user: sapmachine
        register: sapmachine_pw

      - name: read Jenkins Slave secret
        command: "docker exec ci bash /usr/share/jenkins/read-slave-secret.sh {{ jenkins_slave_name }}"
        become: yes
        become_user: jenkins
        register: slave_secret

      - name: start Jenkins Slave
        command: "/home/jenkins/start-slave.sh {{ jenkins_master_url }} {{ slave_secret.stdout }} -noCertificateCheck"
        args:
          chdir: /home/jenkins
        become: yes
        become_user: jenkins

      - name: show Jenkins SapMachine password
        debug:
          msg:
            - "user: SapMachine"
            - "password: {{ sapmachine_pw.stdout }}"
